[build]
    functions="functions"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200
  query = {path = ":path"} #  apply this rule for /old-path?path=example
